### ISSUE TITLE
応用1の12（２つの文字列間の類似度・距離）

### ISSUE THREAD

**Issue by toyokazu** [ksuap/bugreport#9]
「編集距離（Edit Distance; Levenshtein Distance）」の「表の初期化処理」の記述ですが，

```
結果として，一番上の行，一番左の列のみに数値が入れられた表が得られます． 値は，左（下）になるにつれ1ずつ増えていきます．
```
となっているところの，「左（下）」は「右（下）」でしょうか？

**Comment by tamada** [comment]
ありがとうございます．その通りです．
修正しました．
